/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jacoco2slack.app;

import jacoco2slack.list.LinkedList;

import static jacoco2slack.utilities.StringUtils.join;
import static jacoco2slack.utilities.StringUtils.split;
import static jacoco2slack.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
