name: Submit Java Code Coverage to Slack

on:
  schedule:
    # 毎週金曜日の 09:00 に起動
    # (UTC の 00:00 は JST の 09:00)
    - cron: '0 3 * * FRI'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
      - name: Submit coverage to Slack
        shell: bash
        env:
          SLACK_URL: ${{ secrets.SLACK_URL }}
        run: ./submit-coverage-to-slack.sh "$SLACK_URL"
